---
  - name: Install nexus through Docker
    hosts: localhost
    become: true
    tasks:
      - name: Install Docker
        apt:
          name: docker.io
          state: present
      
      - name: Run nexus image
        shell: sudo docker run -d -p 8081:8081 --name nexus sonatype/nexus3