---
- name: Install jenkins in cluster nodes
  hosts: cluster_nodes
  tasks:
    - name: Update nodes
      become: true
      apt:
        update_cache: yes

    - name: Install curl, openjdk
      become: true
      apt:
        name: "{{ item }}"
        state: present
      loop:
          - curl
          - openjdk-17-jre

    - name: Get jenkins packages
      shell : curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee \
              /usr/share/keyrings/jenkins-keyring.asc > /dev/null

    - name: Sign packages
      shell : echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
              https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
              /etc/apt/sources.list.d/jenkins.list > /dev/null

    - name: Update nodes
      become: true
      apt:
        update_cache: yes

    - name: Install jenkins
      become: true
      apt:
        name: jenkins
        state: present