---
  - name: Install grafana through Docker
    hosts: localhost
    become: true
    tasks:
      - name: Install Docker
        apt:
          name: docker.io
          state: present
      
      - name: Run nexus image
        shell: sudo docker run -d --name=grafana -p 3000:3000 grafana/grafana